function test_mario_paz_modal()
%TEST_MARIO_PAZ_MODAL Reproduce Illustrative Example 11.1 from Mario Paz.
% The benchmark is the two-member plane frame in Fig. 11.7. The exterior
% nodes are fixed, leaving ux, uy, and rz at the corner node as the three
% free coordinates. Published values are rounded, so the test also records
% the corresponding full-precision values for the exact 100-inch geometry.

options = struct('verbose', false, 'plotting', false);
problem = StructFEProblem('CaseFig11.7p363 MarioPaz.txt', options);
model = problem.GetAnalysisModel();
result = problem.RunModal();

diagonalProjection = 100 / sqrt(2);
expectedCoordinates = [0, 0; ...
    diagonalProjection, diagonalProjection; ...
    diagonalProjection + 100, diagonalProjection];
assertClose(model.nodeCoordinates, expectedCoordinates, ...
    0, 5e-13, 'The benchmark geometry is not the exact Fig. 11.7 geometry.');
assertClose([model.elementData.length], [100, 100], ...
    0, 1e-12, 'The Mario Paz members must both be 100 inches long.');

assert(isequal(result.fixedDOFs, [1 2 3 7 8 9]));
assert(isequal(result.freeDOFs, [4 5 6]));

% Exact forms behind the rounded matrices printed on pages 364-365.
rootTwo = sqrt(2);
expectedK = 1e6 * [ ...
    0.906, 0.294, 0.3*rootTwo; ...
    0.294, 0.318, 0.6 - 0.3*rootTwo; ...
    0.3*rootTwo, 0.6 - 0.3*rootTwo, 80];
expectedM = [ ...
    288, -8, 1100*rootTwo; ...
    -8, 304, 2200 - 1100*rootTwo; ...
    1100*rootTwo, 2200 - 1100*rootTwo, 80000];

reducedK = full(model.stiffness(result.freeDOFs, result.freeDOFs));
reducedM = full(model.mass(result.freeDOFs, result.freeDOFs));
assertClose(reducedK, expectedK, 1e-12, 1e-8, ...
    'The assembled stiffness matrix does not match the Paz benchmark.');
assertClose(reducedM, expectedM, 1e-12, 1e-10, ...
    'The assembled mass matrix does not match the Paz benchmark.');

% Full-precision roots corresponding to the rounded values
% {638.5, 976.6, 4211.6} printed in the book.
expectedEigenvalues = [ ...
    638.5045874481652; ...
    976.5825465395019; ...
    4211.597108802472];
expectedAngularFrequencies = [ ...
    25.26864831066682; ...
    31.25032074298601; ...
    64.89681894209048];
expectedFrequenciesHz = [ ...
    4.021630283893296; ...
    4.973643019453416; ...
    10.328649525573443];

assertClose(result.eigenvalues, expectedEigenvalues, 1e-10, 1e-10, ...
    'The modal eigenvalues do not reproduce the Paz benchmark.');
assertClose(result.angularFrequenciesRadPerSec, ...
    expectedAngularFrequencies, 1e-10, 1e-11, ...
    'The angular frequencies do not reproduce the Paz benchmark.');
assertClose(result.frequenciesHz, expectedFrequenciesHz, ...
    1e-10, 1e-12, ...
    'The natural frequencies do not reproduce the Paz benchmark.');

% These checks use tolerances implied by the number of digits printed in
% the source. They make the relationship to the published table explicit
% without expecting rounded decimal values to compare exactly.
assertClose(result.eigenvalues, [638.5; 976.6; 4211.6], ...
    0, 0.051, 'The eigenvalues disagree with the published rounded values.');
assertClose(result.frequenciesHz, [4.02; 4.97; 10.33], ...
    0, 0.0051, ...
    'The frequencies disagree with the published rounded values.');

% Eigenvectors have arbitrary signs. Normalize each computed vector by its
% modal mass, then align its sign with the corresponding published vector.
expectedModes = [ ...
     0.0218297465698063, 0.00497889279808637,  0.0583073725558010; ...
    -0.0527016702319938, 0.00206232492256900,  0.0241517044989536; ...
     0,                  0.00340928637493526, -0.00162914990314308];
computedModes = result.modeShapes(result.freeDOFs, :);
for modeNumber = 1:size(computedModes, 2)
    modalMass = computedModes(:, modeNumber).' * reducedM * ...
        computedModes(:, modeNumber);
    assert(isfinite(modalMass) && modalMass > 0);
    computedModes(:, modeNumber) = ...
        computedModes(:, modeNumber) / sqrt(modalMass);
    if computedModes(:, modeNumber).' * expectedModes(:, modeNumber) < 0
        computedModes(:, modeNumber) = -computedModes(:, modeNumber);
    end
end

assertClose(computedModes, expectedModes, 1e-9, 1e-11, ...
    'The mass-normalized mode shapes do not reproduce the Paz benchmark.');
assertClose(computedModes.' * reducedM * computedModes, eye(3), ...
    1e-11, 1e-11, 'The mode shapes are not mass orthonormal.');

% A direct eigenpair residual catches a mutually consistent but incorrect
% set of stored reference values or a future mode-shape ordering error.
for modeNumber = 1:3
    modeShape = computedModes(:, modeNumber);
    eigenvalue = result.eigenvalues(modeNumber);
    residual = reducedK * modeShape - ...
        eigenvalue * reducedM * modeShape;
    residualScale = norm(reducedK, inf) * norm(modeShape, inf) + ...
        abs(eigenvalue) * norm(reducedM, inf) * norm(modeShape, inf);
    if norm(residual, inf) > 1e-12 * residualScale
        error('MKEF:VerificationFailed', ...
            'Mario Paz mode %d has an excessive eigenpair residual.', ...
            modeNumber);
    end
end

assert(all(all(result.modeShapes(result.fixedDOFs, :) == 0)));
end

function assertClose(actual, expected, relativeTolerance, ...
        absoluteTolerance, message)
difference = max(abs(actual(:) - expected(:)));
scale = max(abs(expected(:)));
if isempty(difference)
    difference = 0;
end
if isempty(scale)
    scale = 0;
end
limit = absoluteTolerance + relativeTolerance * scale;
if difference > limit
    error('MKEF:VerificationFailed', '%s Error=%g, tolerance=%g.', ...
        message, difference, limit);
end
end
