function test_reference_examples()
%TEST_REFERENCE_EXAMPLES Run every tutorial lab quietly from another directory.

testsDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(testsDir);
examplesDir = fullfile(rootDir, 'reference', 'examples');
previousDir = pwd;
cleanup = onCleanup(@() cd(previousDir));

addpath(examplesDir);
cd(testsDir);
results = run_reference_examples(false);

expectedFields = { ...
    'example_01_element_matrices', ...
    'example_02_sparse_assembly', ...
    'example_03_static_bar', ...
    'example_04_load_histories', ...
    'example_05_modal_frame', ...
    'example_06_newmark_sdof', ...
    'example_07_result_recovery', ...
    'example_08_pinned_portal_uniform'};

actualFields = fieldnames(results);
assert(numel(actualFields) == numel(expectedFields), ...
    'MKEF:VerificationFailed: unexpected number of reference results.');
for i = 1:numel(expectedFields)
    assert(isfield(results, expectedFields{i}), ...
        ['MKEF:VerificationFailed: missing reference result ' ...
         expectedFields{i} '.']);
    assert(isstruct(results.(expectedFields{i})), ...
        ['MKEF:VerificationFailed: reference result is not a struct: ' ...
         expectedFields{i} '.']);
end

clear cleanup;
end
