function test_preprocessor_site()
%TEST_PREPROCESSOR_SITE Verify offline assets and browser safety invariants.

testsDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(testsDir);
preDir = fullfile(rootDir, 'preprocessor');
pages = {fullfile(preDir, 'index.html'), ...
    fullfile(preDir, 'tests', 'index.html')};

for pageIndex = 1:numel(pages)
    page = pages{pageIndex};
    assert(exist(page, 'file') == 2, ...
        ['MKEF:VerificationFailed: missing preprocessor page ' page '.']);
    html = fileread(page);
    assert(isempty(regexpi(html, '<script[^>]+type=["'']module', 'once')), ...
        'MKEF:VerificationFailed: preprocessor uses file-restricted modules.');
    assert(isempty(regexpi(html, ...
        '(?:src|href)\s*=\s*["''](?:https?:)?//', 'once')), ...
        'MKEF:VerificationFailed: preprocessor has an external runtime asset.');
    targets = regexp(html, '(?:src|href)\s*=\s*["'']([^"'']+)["'']', 'tokens');
    for i = 1:numel(targets)
        target = targets{i}{1};
        if isempty(target) || target(1) == '#'
            continue;
        end
        targetPath = fullfile(fileparts(page), strrep(target, '/', filesep));
        assert(exist(targetPath, 'file') == 2, ...
            ['MKEF:VerificationFailed: unresolved preprocessor asset ' target '.']);
    end
end

requiredIds = {'analysis-type', 'element-type', 'time-step', 'duration', ...
    'monitor-node', 'monitor-dof', 'viewport', 'case-preview', ...
    'grid-enabled', 'snap-enabled', 'grid-spacing', 'place-node', 'canvas-tool-hint', ...
    'selected-node-x', 'selected-node-y', ...
    'nodes-body', 'elements-body', 'supports-body', 'loads-body'};
mainHtml = fileread(fullfile(preDir, 'index.html'));
assert(~isempty(strfind(mainHtml, 'preserveAspectRatio="xMidYMid meet"')), ...
    'MKEF:VerificationFailed: preprocessor SVG aspect policy is missing.');
assert(isempty(strfind(mainHtml, 'id="add-node"')) && ...
       ~isempty(strfind(mainHtml, 'id="place-node" type="button" data-tool="node"')), ...
    'MKEF:VerificationFailed: Place node must replace insertion at the origin.');
layoutCss = fileread(fullfile(preDir, 'assets', 'preprocessor.css'));
appJs = fileread(fullfile(preDir, 'js', 'app.js'));
assert(~isempty(strfind(appJs, 'activateCanvasTool(''member'', selection.index)')) && ...
       ~isempty(strfind(appJs, 'Add element: select second node.')) && ...
       ~isempty(strfind(appJs, 'Add element: select first node.')), ...
    'MKEF:VerificationFailed: Add element does not start from the selected node.');
assert(~isempty(strfind(layoutCss, 'display:flex; flex-direction:column;')) && ...
       ~isempty(strfind(layoutCss, 'flex:2 1 360px;')), ...
    'MKEF:VerificationFailed: preprocessor canvas height allocation regressed.');
assert(~isempty(strfind(layoutCss, '.table-actions button { align-self:center; height:32px;')), ...
    'MKEF:VerificationFailed: preprocessor action-button height is not constrained.');
assert(~isempty(strfind(layoutCss, '.table-actions { display:flex; align-items:center; flex:0 0 auto;')) && ...
       ~isempty(strfind(layoutCss, 'flex:.7 1 180px;')), ...
    'MKEF:VerificationFailed: fixed controls can consume flexible workspace height.');
assert(~isempty(strfind(layoutCss, 'height:var(--table-list-height);')) && ...
       ~isempty(strfind(layoutCss, 'overflow-y:scroll;')) && ...
       ~isempty(strfind(layoutCss, 'details[open] { min-height:calc(var(--table-list-height) + 35px);')), ...
    'MKEF:VerificationFailed: expanded model lists can be clipped without an inner scrollbar.');
for i = 1:numel(requiredIds)
    assert(~isempty(strfind(mainHtml, ['id="' requiredIds{i} '"'])), ...
        ['MKEF:VerificationFailed: missing preprocessor control ' ...
         requiredIds{i} '.']);
end

assets = [dir(fullfile(preDir, 'js', '*.js')); ...
          dir(fullfile(preDir, 'assets', '*.css'))];
for i = 1:numel(assets)
    content = fileread(fullfile(assets(i).folder, assets(i).name));
    networkCheck = strrep(content, 'http://www.w3.org/2000/svg', '');
    assert(isempty(regexpi(networkCheck, 'https?://|@import\s|fetch\s*\(', 'once')), ...
        ['MKEF:VerificationFailed: external network dependency in ' assets(i).name '.']);
    if strcmp(assets(i).name(end-2:end), '.js')
        assert(isempty(regexp(content, ...
            'innerHTML|\beval\s*\(|new\s+Function\s*\(', 'once')), ...
            ['MKEF:VerificationFailed: unsafe DOM/code API in ' assets(i).name '.']);
    end
end
end
