(function () {
  'use strict';
  var tests = [], passed = 0;
  function test(name, operation) { tests.push({ name: name, operation: operation }); }
  function assert(condition, message) { if (!condition) throw new Error(message || 'Assertion failed.'); }
  function throws(fragment, operation) { try { operation(); } catch (error) { assert(error.message.indexOf(fragment) >= 0, 'Unexpected error: ' + error.message); return; } throw new Error('Expected an error containing ' + fragment); }
  function fixture(record) { return ['# browser fixture', 'analysis', record || 'static', 'nodes', '2', '0,0,0', '1,0,0', 'elems_113', '1', '113,1,2,0.1,200,10,0.01', 'bcfix', '1', '1,1,0,0,0', 'bcforce_stat', '1', '10,2,5,-2,1', ''].join('\n'); }

  test('parses and serializes a configured static case', function () { var model = MKEFPre.caseFormat.parse(fixture()), text = MKEFPre.caseFormat.serialize(model); assert(model.analysis.type === 'static'); assert(text.indexOf('analysis\nstatic\n') === 0); assert(text.indexOf('bcforce_stat\n1\n10,2,5,-2,1') > 0); });
  test('canonical round trip preserves semantic data', function () { var first = MKEFPre.caseFormat.parse(fixture()), second = MKEFPre.caseFormat.parse(MKEFPre.caseFormat.serialize(first)); assert(JSON.stringify(first) === JSON.stringify(second)); });
  test('legacy cases require a task only at export', function () { var model = MKEFPre.caseFormat.parse(fixture().replace('analysis\nstatic\n', '')); assert(model.analysis.type === ''); throws('Select static', function () { MKEFPre.caseFormat.serialize(model); }); });
  test('transient settings round trip exactly', function () { var text = fixture('transient,0.001,0.01,2,2').replace('bcforce_stat\n1\n10,2,5,-2,1\n', 'bcforce_harm\n1\n11,2,5,-2,1,3\n'), model = MKEFPre.caseFormat.parse(text), output = MKEFPre.caseFormat.serialize(model); assert(model.analysis.timeStep === .001 && model.analysis.monitorDOF === 2); assert(output.indexOf('transient,0.001,0.01,2,2') > 0); });
  test('modal cases reject loads', function () { throws('not valid for modal', function () { MKEFPre.caseFormat.parse(fixture('modal')); }); });
  test('static cases reject time-dependent loads', function () { throws('not valid for static', function () { MKEFPre.caseFormat.parse(fixture().replace('bcforce_stat\n1\n10,', 'bcforce_step\n1\n13,')); }); });
  test('unknown markers report their source line', function () { throws('Line 1', function () { MKEFPre.caseFormat.parse('mystery\n'); }); });
  test('duplicate constraints are detected by DOF', function () { var model = MKEFPre.caseFormat.parse(fixture()); model.supports.push({ type: 2, node: 1 }); assert(MKEFPre.caseFormat.validate(model).some(function (message) { return message.indexOf('duplicates') >= 0; })); });
  test('truss cases reject nonzero nodal moments', function () { var model = MKEFPre.caseFormat.newModel('static', 112); model.nodes = [{ x: 0, y: 0 }, { x: 1, y: 0 }]; model.elements = [{ node1: 1, node2: 2, area: 1, youngsModulus: 1, density: 1, momentOfInertia: null }]; model.loads = [{ type: 10, node: 2, fx: 0, fy: 0, mz: 1, frequency: null }]; assert(MKEFPre.caseFormat.validate(model).some(function (message) { return message.indexOf('truss node') >= 0; })); });
  test('zero-length elements are rejected', function () { var model = MKEFPre.caseFormat.parse(fixture()); model.nodes[1] = { x: 0, y: 0 }; assert(MKEFPre.caseFormat.validate(model).some(function (message) { return message.indexOf('zero length') >= 0; })); });
  test('canonical export groups repeated load types', function () { var model = MKEFPre.caseFormat.parse(fixture()); model.loads.push({ type: 10, node: 2, fx: 1, fy: 0, mz: 0, frequency: null }); var text = MKEFPre.caseFormat.serialize(model); assert(text.indexOf('bcforce_stat\n2\n') > 0); });
  test('exact node coordinate edits are serialized', function () { var model = MKEFPre.caseFormat.parse(fixture()); model.nodes[1].x = 2.25; model.nodes[1].y = -3.5; var text = MKEFPre.caseFormat.serialize(model); assert(text.indexOf('2.25,-3.5,0') > 0); });
  test('renderer exposes model-coordinate grid and axes', function () { var svg = document.getElementById('test-svg'), renderer = new MKEFPre.Renderer(svg); renderer.setGrid(true, .5); renderer.draw(MKEFPre.caseFormat.parse(fixture())); assert(svg.querySelectorAll('.coordinate-grid line').length > 0, 'Grid lines are missing.'); var labels = Array.prototype.map.call(svg.querySelectorAll('.coordinate-axes text'), function (item) { return item.textContent; }).join(' '); assert(labels.indexOf('X') >= 0 && labels.indexOf('Y') >= 0, 'Axis labels are missing.'); });
  test('renderer viewBox follows the full canvas aspect ratio', function () { var svg = document.getElementById('test-svg'), renderer = new MKEFPre.Renderer(svg), rect = svg.getBoundingClientRect(); renderer.view = { x: -1, y: -1, width: 2, height: 2 }; renderer.synchronizeAspectRatio(); assert(Math.abs(renderer.view.width / renderer.view.height - rect.width / rect.height) < 1e-6, 'Canvas and viewBox aspect ratios differ.'); });
  test('node tool shows a dashed placement preview at the normalized point', function () { var svg = document.getElementById('test-svg'), renderer = new MKEFPre.Renderer(svg, { placementPoint: function () { return { x: 2, y: 3 }; } }); renderer.draw(MKEFPre.caseFormat.parse(fixture())); renderer.setTool('node'); renderer.updateNodePreview({ x: 1.8, y: 3.2 }); var preview = svg.querySelector('.node-placement-preview'); assert(preview && preview.getAttribute('visibility') === 'visible', 'Node preview is not visible.'); assert(preview.getAttribute('cx') === '2' && preview.getAttribute('cy') === '-3', 'Node preview does not use normalized coordinates.'); });
  test('member tool can start with the selected node as its first endpoint', function () { var svg = document.getElementById('test-svg'), endpoints = null, renderer = new MKEFPre.Renderer(svg, { addElement: function (first, second) { endpoints = [first, second]; } }); renderer.draw(MKEFPre.caseFormat.parse(fixture())); renderer.setTool('member', 1); assert(svg.querySelector('[data-node-id="2"]').classList.contains('pending'), 'Selected first endpoint is not pending.'); svg.querySelector('[data-node-id="1"]').dispatchEvent(new MouseEvent('click', { bubbles: true })); assert(endpoints && endpoints[0] === 1 && endpoints[1] === 0, 'Member endpoints do not start with the selected node.'); });
  test('member tool retains the first endpoint when creation is rejected', function () { var svg = document.getElementById('test-svg'), renderer = new MKEFPre.Renderer(svg, { addElement: function () { return false; } }); renderer.draw(MKEFPre.caseFormat.parse(fixture())); renderer.setTool('member', 0); svg.querySelector('[data-node-id="2"]').dispatchEvent(new MouseEvent('click', { bubbles: true })); assert(svg.querySelector('[data-node-id="1"]').classList.contains('pending'), 'Rejected creation discarded the first endpoint.'); });
  test('support types use distinct marker geometry', function () { var svg = document.getElementById('test-svg'), model = MKEFPre.caseFormat.parse(fixture()), renderer = new MKEFPre.Renderer(svg); model.nodes = [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }]; model.supports = [{ type: 1, node: 1 }, { type: 2, node: 2 }, { type: 3, node: 3 }, { type: 4, node: 4 }]; renderer.draw(model); assert(svg.querySelector('.support-type-1 .support-ground') && !svg.querySelector('.support-type-1 path'), 'Type 1 fixed marker is missing.'); assert(svg.querySelectorAll('.support-type-2 circle').length === 1 && svg.querySelector('.support-type-2 path'), 'Type 2 horizontal roller marker is missing.'); assert(svg.querySelectorAll('.support-type-3 circle').length === 1 && svg.querySelector('.support-type-3 path'), 'Type 3 vertical roller marker is missing.'); assert(svg.querySelector('.support-type-4 path') && !svg.querySelector('.support-type-4 circle'), 'Type 4 pinned marker is missing.'); });
  test('loads render above every model layer', function () { var svg = document.getElementById('test-svg'), renderer = new MKEFPre.Renderer(svg); renderer.draw(MKEFPre.caseFormat.parse(fixture())); assert(svg.lastElementChild.classList.contains('loads-layer'), 'Loads layer is not topmost.'); });

  document.addEventListener('DOMContentLoaded', function () {
    var output = document.getElementById('test-output'), status = document.getElementById('test-status'), lines = [];
    tests.forEach(function (item) { try { item.operation(); passed += 1; lines.push('PASS  ' + item.name); } catch (error) { lines.push('FAIL  ' + item.name + '\n      ' + error.message); } });
    output.textContent = lines.join('\n'); status.textContent = passed + ' / ' + tests.length + ' tests passed'; status.setAttribute('data-status', passed === tests.length ? 'passed' : 'failed');
  });
}());
