(function (M) {
  'use strict';
  var tests = [];
  function test(name, operation) { tests.push({ name: name, operation: operation }); }
  function assert(condition, message) { if (!condition) throw new Error(message || 'Assertion failed'); }
  function close(actual, expected, tolerance) { assert(Math.abs(actual - expected) <= (tolerance || 1e-10), actual + ' != ' + expected); }
  function fixture() {
    return {
      format: 'mkef-postprocessor', version: 1,
      metadata: { title: 'Browser test', units: { length: 'm', force: 'N', moment: 'N*m', stress: 'Pa', time: 's' } },
      model: { dimension: 2, dofPerNode: 3, dofLabels: ['ux', 'uy', 'rz'],
        nodes: [{ id: 1, x: 0, y: 0 }, { id: 2, x: .5, y: .5 }],
        elements: [{ id: 1, type: 113, nodeIds: [1, 2], properties: { area: 1, youngsModulus: 2, density: 3, momentOfInertia: 4 } }],
        dofMap: [[1, 2, 3], [4, 5, 6]], supports: [{ type: 1, nodeId: 1 }] },
      analysis: { type: 'static', displacements: [0, 0, 0, 0, 0, 0], loadVector: [0, 0, 0, 0, 1, 0], reactions: [0, -1, -4, 0, 0, 0], equilibriumResidual: [0, 0, 0],
        elementResults: [{ elementId: 1, type: 113, localEndForces: [0, -1, -4, 0, 1, 0], axialStrain: 0, axialStress: 0, axialForce: 0 }] }
    };
  }
  function trussFixture() {
    var data = fixture(); data.model.dofPerNode = 2; data.model.dofLabels = ['ux', 'uy']; data.model.dofMap = [[1, 2], [3, 4]];
    data.model.elements[0] = { id: 1, type: 112, nodeIds: [1, 2], properties: { area: 1, youngsModulus: 2, density: 3 } };
    data.analysis.displacements = [0, 0, .01, 0]; data.analysis.loadVector = [0, 0, 10, 0]; data.analysis.reactions = [-10, 0, 0, 0];
    data.analysis.elementResults[0] = { elementId: 1, type: 112, localEndForces: [-10, 0, 10, 0], axialStrain: .002, axialStress: 20, axialForce: 10 };
    return data;
  }
  function modalFixture() {
    var data = fixture(); data.analysis = { type: 'modal', frequenciesHz: [2, 5], angularFrequenciesRadPerSec: [4 * Math.PI, 10 * Math.PI],
      modeShapes: [[0, 0], [0, 0], [0, 0], [.1, -.1], [.2, .3], [.01, -.02]] };
    return data;
  }
  function transientFixture(reduced) {
    var data = fixture(), ids = reduced ? [2] : [1, 2, 3, 4, 5, 6];
    var rows = ids.map(function (id) { return [0, id * .001, id * .002]; });
    data.analysis = { type: 'transient', time: [0, .1, .2], globalDOFIds: ids, displacements: rows, velocities: rows,
      spectrumFrequencyHz: [0, 5, 10], displacementAmplitudeSpectrum: rows,
      sampling: { originalSampleCount: 3, exportedSampleCount: 3, timeStride: 1 } };
    return data;
  }
  function largeFixture(count) {
    var nodes = [], elements = [], dofMap = [], elementResults = [], dofCount = (count + 1) * 2;
    for (var i = 0; i <= count; i += 1) { nodes.push({ id: i + 1, x: i, y: 0 }); dofMap.push([2 * i + 1, 2 * i + 2]); }
    for (var e = 0; e < count; e += 1) { elements.push({ id: e + 1, type: 112, nodeIds: [e + 1, e + 2], properties: { area: 1, youngsModulus: 2, density: 3 } }); elementResults.push({ elementId: e + 1, type: 112, localEndForces: [0, 0, 0, 0], axialStrain: 0, axialStress: 0, axialForce: 0 }); }
    return { format: 'mkef-postprocessor', version: 1, metadata: { title: 'Large', units: { length: '', force: '', moment: '', stress: '', time: '' } },
      model: { dimension: 2, dofPerNode: 2, dofLabels: ['ux', 'uy'], nodes: nodes, elements: elements, dofMap: dofMap, supports: [] },
      analysis: { type: 'static', displacements: new Array(dofCount).fill(0), loadVector: new Array(dofCount).fill(0), reactions: new Array(dofCount).fill(0), equilibriumResidual: [0, 0, 0], elementResults: elementResults } };
  }

  test('schema accepts static, modal, and transient v1 data', function () { assert(M.validateDataset(fixture())); assert(M.validateDataset(modalFixture())); assert(M.validateDataset(transientFixture(false))); });
  test('schema reports the invalid JSON path', function () { var data = fixture(); data.model.elements[0].nodeIds[1] = 99; try { M.validateDataset(data); } catch (error) { assert(error.message.indexOf('$.model.elements[0].nodeIds[1]') === 0); return; } throw new Error('Invalid node reference was accepted'); });
  test('112 interpolation preserves endpoints', function () { var points = M.geometry.sample112({ x: 0, y: 0 }, { x: 2, y: 0 }, { x: 1, y: 2 }, { x: 3, y: 4 }, 2); close(points[0].x, 2); close(points[0].y, 4); close(points[1].x, 8); close(points[1].y, 8); });
  test('113 Hermite interpolation preserves endpoints and rotations', function () { var L = 5, count = 1001, points = M.geometry.sample113({ x: 0, y: 0 }, { x: L, y: 0 }, { x: 0, y: 0, r: .2 }, { x: 0, y: 0, r: -.1 }, 1, count), dx = L / (count - 1); close(points[0].x, 0); close(points[count - 1].x, L); close((points[1].y - points[0].y) / dx, .2, .001); close((points[count - 1].y - points[count - 2].y) / dx, -.1, .001); });
  test('displacement field sampling finds an interior frame maximum', function () { var data = fixture(); data.analysis.displacements = [0, 0, 1, 0, 0, -1]; var dataset = M.validateDataset(data), field = M.staticResults.displacementMagnitudeField(dataset, 31), values = field.byElementId.get(1); close(values[0], 0); close(values[values.length - 1], 0); assert(field.maximum > 0, 'Interior frame displacement was missed'); });
  test('mathematical Y is inverted exactly once', function () { var point = M.geometry.svgPoint({ x: 2, y: 3 }); close(point.x, 2); close(point.y, -3); });
  test('retained renderer preserves nodes and view during updates', function () {
    var svg = document.getElementById('test-svg'), selected = null, dataset = M.validateDataset(fixture()), renderer = new M.Renderer(svg, function (value) { selected = value; });
    renderer.mount(dataset); renderer.updateDeformation(dataset.raw.analysis.displacements, 1, 31);
    var path = renderer.deformedByElement.get(1), viewBox = svg.getAttribute('viewBox'), count = renderer.sceneNodeCount();
    renderer.setVisibility({ showOriginal: false, showDeformed: true, showNodes: true, showNodeLabels: true, showElementLabels: false, showSupports: true, showLoads: true, showReactions: true });
    renderer.updateDeformation([0, 0, 0, .01, .02, 0], 2, 31); renderer.setSelection({ kind: 'element', id: 1 });
    assert(renderer.deformedByElement.get(1) === path, 'Deformed path was rebuilt'); assert(renderer.sceneNodeCount() === count, 'DOM node count changed'); assert(svg.getAttribute('viewBox') === viewBox, 'View reset during update'); assert(selected.id === 1, 'Selection callback failed');
  });
  test('node pointer clicks select original and deformed positions without starting pan', function () { var svg = document.getElementById('test-svg'), selected = null, dataset = M.validateDataset(fixture()), renderer = new M.Renderer(svg, function (value) { selected = value; }); renderer.mount(dataset); var node = renderer.nodeById.get(2); node.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, button: 0, pointerId: 7 })); assert(renderer.drag === null, 'Node press started viewport panning'); node.dispatchEvent(new MouseEvent('click', { bubbles: true })); assert(selected && selected.kind === 'node' && selected.id === 2, 'Original node click did not select'); assert(renderer.nearestNodeId({ x: .5, y: -.5 }, false) === 2, 'Original overlap resolution chose the wrong node'); renderer.updateDeformation([0, 0, 0, .01, .02, 0], 10, 31); var deformedHit = renderer.deformedNodeHitById.get(2); close(Number(deformedHit.getAttribute('cx')), .6); close(Number(deformedHit.getAttribute('cy')), -.7); assert(renderer.nearestNodeId({ x: .6, y: -.7 }, true) === 2, 'Deformed overlap resolution chose the wrong node'); deformedHit.dispatchEvent(new MouseEvent('click', { bubbles: true })); assert(selected && selected.id === 2 && deformedHit.classList.contains('selected'), 'Deformed node click did not select'); });
  test('SVG labels use model-relative size and bounded halo', function () { var svg = document.getElementById('test-svg'), label = svg.querySelector('.label'); assert(Number(label.getAttribute('font-size')) < 1, 'Label is not model-relative'); assert(parseFloat(getComputedStyle(label).strokeWidth) < parseFloat(getComputedStyle(label).fontSize), 'Text halo exceeds font size'); });
  test('static symbols distinguish reaction force and moment', function () { var svg = document.getElementById('test-svg'), dataset = M.validateDataset(fixture()), renderer = new M.Renderer(svg); renderer.mount(dataset); M.staticResults.mount(renderer, dataset); var force = svg.querySelector('.reaction-force-symbol'), moment = svg.querySelector('.reaction-moment-symbol'); assert(svg.querySelectorAll('.support-marker').length === 1); assert(svg.querySelectorAll('.load-symbol').length > 0); assert(force && moment); assert(getComputedStyle(force).stroke !== getComputedStyle(moment).stroke, 'Reaction colors are identical'); assert(parseFloat(getComputedStyle(force).strokeWidth) > 2, 'Reaction force is not thicker'); assert(parseFloat(getComputedStyle(moment).strokeWidth) > 2, 'Reaction moment is not thicker'); renderer.setSelection({ kind: 'node', id: 1 }); assert(!force.classList.contains('selected') && !moment.classList.contains('selected'), 'Node selection obscured reaction styles'); });
  test('postprocessor uses all four shared support markers', function () { var data = fixture(); data.model.supports = [{ type: 1, nodeId: 1 }, { type: 2, nodeId: 1 }, { type: 3, nodeId: 2 }, { type: 4, nodeId: 2 }]; var svg = document.getElementById('test-svg'), renderer = new M.Renderer(svg); renderer.mount(M.validateDataset(data)); assert(svg.querySelector('.support-type-1 .support-ground') && !svg.querySelector('.support-type-1 path'), 'Type 1 fixed marker is missing.'); assert(svg.querySelector('.support-type-2 circle') && svg.querySelector('.support-type-2 path'), 'Type 2 marker is missing.'); assert(svg.querySelector('.support-type-3 circle') && svg.querySelector('.support-type-3 path'), 'Type 3 marker is missing.'); assert(svg.querySelector('.support-type-4 path') && !svg.querySelector('.support-type-4 circle'), 'Type 4 pinned marker is missing.'); assert(svg.querySelector('.support-type-2 title').textContent.indexOf('free ux only') >= 0 && svg.querySelector('.support-type-3 title').textContent.indexOf('free uy only') >= 0, 'Single-free-DOF support names are ambiguous.'); });
  test('deflection result creates a sparse gradient legend and retains paths', function () { var dataset = M.validateDataset(trussFixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var path = renderer.deformedByElement.get(1), legend = M.staticResults.applyResult(renderer, dataset, 'displacementMagnitude', 31), stroke = path.style.stroke; assert(legend.kind === 'color' && legend.ticks.length === 3 && legend.unit === 'm', 'Deflection legend is incomplete'); assert(renderer.resultDefs.querySelectorAll('linearGradient').length === 1); assert(renderer.resultDefs.querySelectorAll('stop').length <= 9, 'Gradient stop cap was exceeded'); renderer.updateDeformation(dataset.raw.analysis.displacements, 25, 31); assert(renderer.deformedByElement.get(1) === path && path.style.stroke === stroke, 'Scale update rebuilt or recolored the path'); close(legend.max, .01); });
  test('zero deflection uses a neutral color and one legend value', function () { var dataset = M.validateDataset(fixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var legend = M.staticResults.applyResult(renderer, dataset, 'displacementMagnitude', 31), stroke = getComputedStyle(renderer.deformedByElement.get(1)).stroke; assert(legend.ticks.length === 1 && legend.ticks[0] === 0, 'Zero legend is not singular'); assert(renderer.resultDefs.childNodes.length === 0, 'Zero field created gradients'); assert(stroke === 'rgb(102, 120, 138)', 'Unexpected neutral color ' + stroke); });
  test('selected static node details focus on displacement and nonzero actions', function () { var dataset = M.validateDataset(trussFixture()), lines = M.staticResults.nodeDetails(dataset, 2).join('\n'); assert(lines.indexOf('|u| = 0.01 m') >= 0); assert(lines.indexOf('ux=0.01 m') >= 0 && lines.indexOf('uy=0 m') >= 0); assert(lines.indexOf('Load: Fx=10 N') >= 0); assert(lines.indexOf('Reaction:') < 0); assert(lines.indexOf('Global DOFs') < 0 && lines.indexOf('Coordinates') < 0); });
  test('selected node reports the displayed element-end result', function () { var frame = M.validateDataset(fixture()), moment = M.staticResults.nodeResultDetails(frame, 1, 'M').join('\n'), truss = M.staticResults.nodeResultDetails(M.validateDataset(trussFixture()), 2, 'axialForce').join('\n'); assert(moment.indexOf('Displayed bending moment M') >= 0 && moment.indexOf('E1 · end 1 = 4 N*m') >= 0, 'Frame diagram value is missing at the selected node.'); assert(truss.indexOf('Displayed axial force') >= 0 && truss.indexOf('E1 · end 2 = 10 N') >= 0, 'Truss result value is missing at the selected node.'); });
  test('frame diagram convention and retained overlay are correct', function () { var q = [0, -100, -50, 0, 100, 0]; close(M.staticResults.frameDiagram(q, 'N', .4), 0); close(M.staticResults.frameDiagram(q, 'V', .4), 100); close(M.staticResults.frameDiagram(q, 'M', 0), 50); close(M.staticResults.frameDiagram(q, 'M', 1), 0); var dataset = M.validateDataset(fixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var base = renderer.deformedByElement.get(1), legend = M.staticResults.applyResult(renderer, dataset, 'M'); assert(legend.text.indexOf('M diagram') === 0); assert(renderer.deformedByElement.get(1) === base); assert(renderer.layers.diagrams.querySelectorAll('[data-element-id]').length > 0); });
  test('truss coloring is signed without canvas labels', function () { var dataset = M.validateDataset(trussFixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); M.staticResults.applyResult(renderer, dataset, 'axialForce'); assert(renderer.deformedByElement.get(1).style.stroke !== ''); assert(!renderer.svg.querySelector('.result-label')); });
  test('modal canonicalization is deterministic and does not mutate JSON', function () { var data = modalFixture(), original = JSON.stringify(data.analysis.modeShapes), dataset = M.validateDataset(data), canonical = M.modalView.canonicalMode(dataset, 1); assert(JSON.stringify(data.analysis.modeShapes) === original, 'Source mode matrix was mutated'); assert(canonical.pivotDOF === 5 && canonical.sign === 1); close(canonical.vector[3], -1 / 3); close(canonical.vector[4], 1); close(canonical.vector[5], -1 / 15); assert(canonical.vector[0] === 0 && canonical.vector[1] === 0 && canonical.vector[2] === 0, 'Fixed DOFs changed'); });
  test('modal sign uses the earliest tied translational component', function () { var data = modalFixture(); data.analysis.modeShapes = [[0], [0], [0], [-.5], [.5], [.25]]; data.analysis.frequenciesHz = [2]; data.analysis.angularFrequenciesRadPerSec = [4 * Math.PI]; var canonical = M.modalView.canonicalMode(M.validateDataset(data), 0); assert(canonical.pivotDOF === 4 && canonical.sign === -1); close(canonical.vector[3], 1); close(canonical.vector[4], -1); close(canonical.vector[5], -.5); });
  test('modal display has a stable sampled peak scale', function () { var dataset = M.validateDataset(modalFixture()), canonical = M.modalView.canonicalMode(dataset, 1), automatic = M.geometry.automaticScale(dataset, canonical.vector, 31), result = M.modalView.display(dataset, 1, 2, 31); close(result.peakScale, 2 * automatic.scale); close(result.scale, result.peakScale); close(result.frequencyHz, 5); assert(!result.zero); });
  test('rotation-only modal shapes render and all-zero modes are disabled', function () { var data = modalFixture(); data.analysis.modeShapes = [[0, 0], [0, 0], [.1, 0], [0, 0], [0, 0], [-.2, 0]]; var dataset = M.validateDataset(data), rotational = M.modalView.display(dataset, 0, 1, 31), zero = M.modalView.display(dataset, 1, 1, 31); assert(!rotational.zero && rotational.pivotDOF === 6 && Number.isFinite(rotational.peakScale) && rotational.peakScale > 0, 'Rotation-only mode was suppressed'); close(rotational.vector[2], -.5); close(rotational.vector[5], 1); assert(zero.zero); close(zero.peakScale, 0); });
  test('modal phase math covers peaks, zero, speed, and navigation bounds', function () { var vector = [1, -2, 0], negative = M.modalView.phaseVector(vector, -1), zero = M.modalView.phaseVector(vector, 0); assert(negative[0] === -1 && negative[1] === 2 && zero.every(function (value) { return value === 0; })); close(M.modalView.phaseAt(0, 0, 1).factor, 1); close(M.modalView.phaseAt(0, 500, 1).factor, 0); close(M.modalView.phaseAt(0, 1000, 1).factor, -1); close(M.modalView.phaseAt(0, 500, 2).factor, -1); close(M.modalView.phaseAngleForFactor(-1), Math.PI); assert(M.modalView.clampModeIndex(-1, 2) === 0 && M.modalView.clampModeIndex(5, 2) === 1); });
  test('transient full and reduced exports are distinguished', function () { var full = M.validateDataset(transientFixture(false)), reduced = M.validateDataset(transientFixture(true)); assert(M.transientView.hasFullDisplacements(full)); assert(!M.transientView.hasFullDisplacements(reduced)); close(M.transientView.vectorAt(full, 'displacements', 2)[5], .012); assert(M.transientView.vectorAt(reduced, 'displacements', 1)[0] === undefined, 'Missing DOF was represented as zero'); assert(M.transientView.series(reduced, 2, 'displacements').y.length === 3); });
  test('transient histories retain exact samples and report physical units', function () { var dataset = M.validateDataset(transientFixture(false)), translation = M.transientView.series(dataset, 4, 'velocities'), rotation = M.transientView.series(dataset, 6, 'displacements'), spectrum = M.transientView.series(dataset, 4, 'spectrum'); assert(translation.y === dataset.raw.analysis.velocities[3], 'History samples were copied or changed'); assert(translation.yLabel.indexOf('m/s') >= 0 && translation.yLabel.indexOf('ux') >= 0); assert(rotation.yLabel.indexOf('rad') >= 0 && spectrum.yLabel.indexOf('m') >= 0); close(translation.y[2], .008); });
  test('transient field and decimation metadata expose omissions', function () { var data = transientFixture(false); delete data.analysis.velocities; data.analysis.sampling = { originalSampleCount: 9, exportedSampleCount: 3, timeStride: 4 }; var dataset = M.validateDataset(data), fields = M.transientView.fieldStatus(dataset), sampling = M.transientView.samplingSummary(dataset); assert(fields.present.indexOf('displacements') >= 0 && fields.omitted.indexOf('velocities') >= 0 && fields.omitted.indexOf('reactions') >= 0); assert(sampling.decimated && sampling.original === 9 && sampling.exported === 3 && sampling.stride === 4); });
  test('transient playback uses exported time values, stride, and exact boundaries', function () { var time = [0, .1, 1, 2]; assert(M.transientView.stepFrameIndex(0, -1, 4, 2) === 0); assert(M.transientView.stepFrameIndex(0, 1, 4, 2) === 2); assert(M.transientView.stepFrameIndex(2, 1, 4, 2) === 3); assert(M.transientView.playbackFrames(4, 0, 2).join(',') === '0,2,3'); assert(M.transientView.playbackFrame(time, 0, 2500, 1, 2, 5000).index === 2, 'Nonuniform exported time was ignored'); var end = M.transientView.playbackFrame(time, 1, 5000, 1, 2, 5000); assert(end.index === 3 && end.complete); assert(M.transientView.playbackFrame(time, 2, 0, 1, 1, 5000).index === 2, 'Resume did not start at the retained frame'); });
  test('transient schema rejects incomplete spectrum pairs and impossible sampling metadata', function () { var missing = transientFixture(false); delete missing.analysis.displacementAmplitudeSpectrum; try { M.validateDataset(missing); throw new Error('Incomplete spectrum was accepted'); } catch (error) { assert(error.message.indexOf('must be provided together') >= 0); } var sampling = transientFixture(false); sampling.analysis.sampling.originalSampleCount = 2; try { M.validateDataset(sampling); throw new Error('Impossible sample counts were accepted'); } catch (error) { assert(error.message.indexOf('cannot be smaller') >= 0); } });
  test('history downsampling preserves extrema and point budget', function () { var x = [], y = []; for (var i = 0; i < 10000; i += 1) { x.push(i); y.push(i === 5001 ? 100 : Math.sin(i)); } var result = M.transientView.downsample({ x: x, y: y, xLabel: 'x', yLabel: 'y' }, 2000); assert(result.x.length <= 2000); assert(Math.max.apply(null, result.y) === 100); });
  test('chart renders cursor and retains original tooltip samples', function () { var chart = document.getElementById('test-chart'), x = [], y = []; for (var i = 0; i < 3000; i += 1) { x.push(i); y.push(i * 2); } M.charts.render(chart, { x: x, y: y, xLabel: 'Time', yLabel: 'u' }, 1); assert(chart.querySelector('.chart-series')); assert(chart.querySelector('.chart-cursor')); assert(chart.querySelector('.chart-hit-area')); assert(chart.__chartState.series.x.length === 3000, 'Original chart samples were discarded'); });
  test('chart keyboard selection reports an original sample', function () { var chart = document.getElementById('test-chart'), selected = null; M.charts.render(chart, { x: [0, .1, .2], y: [0, 2, 4], xLabel: 'Time', yLabel: 'u' }, .1, function (index, x, y) { selected = [index, x, y]; }); chart.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true })); assert(selected && selected[0] === 0 && selected[1] === 0 && selected[2] === 0); });
  test('standalone SVG embeds safe styles, chart, and deflection legend', function () { var dataset = M.validateDataset(trussFixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var legend = M.staticResults.applyResult(renderer, dataset, 'displacementMagnitude', 31), text = M.exporting.serialize(document.getElementById('test-svg'), { title: '<unsafe & title>', analysisType: 'static' }, document.getElementById('test-chart'), legend); assert(text.indexOf('xmlns="http://www.w3.org/2000/svg"') >= 0); assert(text.indexOf('&lt;unsafe &amp; title&gt;') >= 0); assert(text.indexOf('reaction-force-symbol') >= 0 && text.indexOf('reaction-moment-symbol') >= 0); assert(text.indexOf('chart-series') >= 0); assert(text.indexOf('data-export-legend') >= 0 && text.indexOf('Displacement magnitude |u| [m]') >= 0); assert(text.indexOf('http://') === text.indexOf('http://www.w3.org/2000/svg')); });
  test('modal export captures current phase metadata, caption, and geometry', function () { var dataset = M.validateDataset(modalFixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var modal = M.modalView.display(dataset, 1, 1.5, 31), scale = modal.peakScale * -.5; renderer.updateDeformation(modal.vector, scale, 31); var sourcePath = renderer.deformedByElement.get(1).getAttribute('d'), context = { title: 'Modal snapshot', analysisType: 'modal', modalModeNumber: 2, modalFrequencyHz: 5, modalAngularFrequencyRadPerSec: 10 * Math.PI, modalPhaseRadians: 2 * Math.PI / 3, modalPhaseFactor: -.5, modalDisplayMultiplier: 1.5, modalPeakScale: modal.peakScale, modalEffectiveScale: scale, captionLines: ['Mode 2 · f = 5 Hz', 'Illustrative phase q = -0.5', 'Normalized arbitrary amplitude'] }, prepared = M.exporting.prepareSvg(document.getElementById('test-svg'), context, null, null); renderer.updateDeformation(modal.vector, modal.peakScale, 31); assert(prepared.querySelector('.deformed-element').getAttribute('d') === sourcePath, 'Prepared export changed after the live scene advanced'); var text = new XMLSerializer().serializeToString(prepared); assert(text.indexOf('modalPhaseFactor') >= 0 && text.indexOf('data-export-caption') >= 0 && text.indexOf('Mode 2') >= 0 && text.indexOf('q = -0.5') >= 0); });
  test('transient export freezes the current frame and includes sampling metadata', function () { var dataset = M.validateDataset(transientFixture(false)), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); renderer.updateDeformation(M.transientView.vectorAt(dataset, 'displacements', 1), 10, 31); var sourcePath = renderer.deformedByElement.get(1).getAttribute('d'), context = { title: 'Transient snapshot', analysisType: 'transient', transientTime: .1, transientSampleNumber: 2, transientSampling: { original: 3, exported: 3, stride: 1, decimated: false }, historyQuantity: 'displacements', captionLines: ['Transient sample 2 / 3 · t = 0.1 s', 'Sampling: 3 of 3 samples exported'] }, prepared = M.exporting.prepareSvg(document.getElementById('test-svg'), context, document.getElementById('test-chart'), null); renderer.updateDeformation(M.transientView.vectorAt(dataset, 'displacements', 2), 10, 31); assert(prepared.querySelector('.deformed-element').getAttribute('d') === sourcePath, 'Prepared transient frame changed after capture'); var text = new XMLSerializer().serializeToString(prepared); assert(text.indexOf('transientSampling') >= 0 && text.indexOf('Transient sample 2') >= 0 && text.indexOf('data-export-caption') >= 0); });
  test('PNG rasterization produces a nonempty blob with a legend', function () { var dataset = M.validateDataset(trussFixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var legend = M.staticResults.applyResult(renderer, dataset, 'displacementMagnitude', 31); return M.exporting.pngBlob(document.getElementById('test-svg'), { title: 'PNG', analysisType: 'static' }, 1, document.getElementById('test-chart'), legend).then(function (blob) { assert(blob.type === 'image/png' && blob.size > 0); }); });
  test('modal PNG rasterization includes the current-frame caption', function () { var dataset = M.validateDataset(modalFixture()), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var modal = M.modalView.display(dataset, 0, 1, 31), context = { title: 'Modal PNG', analysisType: 'modal', modalPhaseFactor: .25, captionLines: ['Mode 1 · f = 2 Hz', 'Illustrative phase q = 0.25'] }; renderer.updateDeformation(modal.vector, modal.peakScale * .25, 31); return M.exporting.pngBlob(document.getElementById('test-svg'), context, 1, null, null).then(function (blob) { assert(blob.type === 'image/png' && blob.size > 0); }); });
  test('transient PNG rasterization captures the visible frame and chart', function () { var dataset = M.validateDataset(transientFixture(false)), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); renderer.updateDeformation(M.transientView.vectorAt(dataset, 'displacements', 2), 10, 31); var context = { title: 'Transient PNG', analysisType: 'transient', transientSampleNumber: 3, transientTime: .2, captionLines: ['Transient sample 3 / 3 · t = 0.2 s', 'Current history value · 0.012 m'] }; return M.exporting.pngBlob(document.getElementById('test-svg'), context, 1, document.getElementById('test-chart'), null).then(function (blob) { assert(blob.type === 'image/png' && blob.size > 0); }); });
  test('2,000-element retained scene meets interaction targets', function () { var started = performance.now(), dataset = M.validateDataset(largeFixture(2000)), renderer = new M.Renderer(document.getElementById('test-svg')); renderer.mount(dataset); var mountElapsed = performance.now() - started; started = performance.now(); M.staticResults.applyResult(renderer, dataset, 'displacementMagnitude', 5); var resultElapsed = performance.now() - started; started = performance.now(); renderer.setVisibility({ showOriginal: false, showDeformed: true, showNodes: true, showNodeLabels: false, showElementLabels: false, showSupports: true, showLoads: true, showReactions: true }); var toggleElapsed = performance.now() - started; started = performance.now(); renderer.updateDeformation(dataset.raw.analysis.displacements, 1, 5); var updateElapsed = performance.now() - started; assert(renderer.layers['deformed-geometry'].querySelectorAll('.deformed-element').length === 2000, 'Result coloring changed the one-path-per-element model'); assert(mountElapsed < 2000, 'Mount took ' + mountElapsed.toFixed(0) + ' ms'); assert(resultElapsed < 1000, 'Deflection result took ' + resultElapsed.toFixed(0) + ' ms'); assert(toggleElapsed < 50, 'Layer toggle took ' + toggleElapsed.toFixed(0) + ' ms'); assert(updateElapsed < 250, 'Deformation update took ' + updateElapsed.toFixed(0) + ' ms'); });

  document.addEventListener('DOMContentLoaded', async function () {
    var lines = [], failed = 0;
    for (var i = 0; i < tests.length; i += 1) { var entry = tests[i]; try { await entry.operation(); lines.push('PASS ' + entry.name); } catch (error) { failed += 1; lines.push('FAIL ' + entry.name + ': ' + error.message); } }
    var smokeFixture = fixture(); smokeFixture.analysis.displacements = [0, 0, 0, .015, -.025, -.01];
    var smokeData = M.validateDataset(smokeFixture), smokeRenderer = new M.Renderer(document.getElementById('visual-smoke'));
    smokeRenderer.mount(smokeData); M.staticResults.mount(smokeRenderer, smokeData);
    smokeRenderer.updateDeformation(smokeData.raw.analysis.displacements, 1, 31);
    smokeRenderer.setVisibility({ showOriginal: true, showDeformed: true, showNodes: true, showNodeLabels: true, showElementLabels: true, showSupports: true, showLoads: true, showReactions: true });
    M.staticResults.applyResult(smokeRenderer, smokeData, 'displacementMagnitude', 31); smokeRenderer.fit();
    document.getElementById('test-output').textContent = lines.join('\n') + '\n\n' + (failed ? failed + ' failed' : tests.length + ' passed');
    document.body.setAttribute('data-test-status', failed ? 'failed' : 'passed');
  });
}(window.MKEFPost));
