// Generated by scripts/generate-support-catalog.cjs. Do not edit.
window.MKEFSupportDefinitions = {"frame":[[1,1,1],[0,1,1],[1,0,1],[1,1,0],[1,0,0],[0,1,0],[0,0,1]],"truss":[[1,1,0],[0,1,0],[1,0,0],[1,1,0],[1,0,0],[0,1,0]]};
